name: aes_vs_fxd_test
paths: 5000
initial_price: 4000
notional: 400000000
stress_factor: 1.0
garch_params: garch_params.json

trader_arrival:
  enabled: true
  pairs_per_tick: 1
  equity_distribution: fixed
  equity_dist_params: 
    value: 50000.0
  leverage_range: [2.0, 10.0]

models:
  - name: AES_es99
    backend: numba
    im:
      type: es
      conf: 0.99
    breaker:
      soft: 1.0
      hard: 2.0
      multipliers: [1.0, 1.5, 2.0]
    liquidation:
      type: partial
      slippage: 0.001

  - name: FXD_20x
    backend: numba
    im:
      type: fixed_leverage
      leverage: 20
    breaker:
      soft: .inf
      hard: .inf
      multipliers: [1.0, 1.0, 1.0]
    liquidation:
      type: full
      slippage: 0.001
