name: aes_vs_fxd_test
paths: 100
initial_price: 4000
stress_factor: 1.5
garch_params: garch_params.json

traders:
  count: 2000
  initial_equity: 50000.0
  behaviors:
    expand_fraction: 0.5
    expand_rate: 0.01
    reduce_fraction: 0.5
    reduce_rate: 0.005

models:
  - name: AES_es99
    backend: numba
    gamma: 0.8
    im:
      type: es
      conf: 0.99
    breaker:
      soft: 1.0
      hard: 2.0
      multipliers: [1.0, 1.5, 2.0]
    liquidation:
      type: partial
      slippage: 0.001

  - name: FXD_20x
    backend: numba
    gamma: 0.8
    im:
      type: fixed_leverage
      leverage: 20
    breaker:
      soft: .inf
      hard: .inf
      multipliers: [1.0, 1.0, 1.0]
    liquidation:
      type: partial
      slippage: 0.001
